version: '3.8'
services:
  node:
    build:
      context: .
    container_name: node
    env_file:
      - .env
    command: sls offline --noPrependStageInUrl --printOutput
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
  dynamodb:
    build:
      context: ./infra/dynamoDb
    container_name: dynamodb
    hostname: dynamodb
    ports:
      - 8000:8000
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/
    volumes:
      - dynamodb_data:/home/dynamodblocal/data
  dynamodb_admin:
    build:
      context: lde/dynamoDbAdmin
    container_name: dynamodb_admin
    ports:
      - 8001:8001

volumes:
  dynamodb_data: