service: express-with-dynamo
plugins:
  - serverless-bundle
  - serverless-dotenv-plugin
  - serverless-offline
provider:
  name: aws
  region: us-east-1
  stage: stage
  runtime: nodejs14.x
  memorySize: 128
functions:
  express-with-dynamo:
    handler: index.handler
    events:
      - http:
          path: /{any+}
          method: ANY
          cors: true
custom:
  serverless-offline:
    host: 0.0.0.0